programs:
	-cd bwa && $(MAKE) && cd ..
	-cd samtools && $(MAKE) && cd ..
	-cd bcftools && $(MAKE) && cd ..

clean:
	-cd bwa && $(MAKE) clean && cd ..
	-cd samtools && $(MAKE) clean && cd ..
	-cd bcftools && $(MAKE) clean && cd ..
